//----------------------------------------------------------------------
//You even want a comment here? Man..
//----------------------------------------------------------------------
language.Add("item_ammo_pistol","Pistol Ammo")
language.Add("item_ammo_pistol_large","Pistol Ammo large")
language.Add("weapon_pistol","Pistol")
language.Add("item_ammo_357_large","357 Ammo Large")
language.Add("item_ammo_357","357 Ammo")
language.Add("weapon_357","357")
language.Add("item_ammo_ar2","Ar2 Ammo")
language.Add("item_ammo_ar2_large","Ar2 Ammo large")
language.Add("weapon_ar2","Ar2")
language.Add("grenade_ar2","Smg1 Grenade")
language.Add("weapon_frag","Grenade")
language.Add("npc_grenade_frag","Grenade")
language.Add("weapon_shotgun","Shotgun")
language.Add("item_box_buckshot","Shotgun Ammo")
language.Add("weapon_crowbar","Crowbar")
language.Add("weapon_stunstick","Stunstick")
language.Add("weapon_bugbait","BugBait")
language.Add("npc_grenade_bugbait","Bug Pheropod")
language.Add("item_ammo_smg1","Smg1 Ammo")
language.Add("item_ammo_smg1_large","Smg1 Ammo Large")
language.Add("weapon_smg1","Smg1")
language.Add("item_ammo_smg1_grenade","Smg1 Grenade")
language.Add("item_ammo_ar2_altfire","Combine Ball")
language.Add("prop_combine_ball","Combine Ball")
language.Add("weapon_crossbow","Crossbow")
language.Add("item_ammo_crossbow","Crossbow Bolts")
language.Add("crossbow_bolt","Crossbow Bolt")
language.Add("weapon_rpg","Rpg")
language.Add("item_rpg_round","Rpg Missile")
language.Add("rpg_missile","Rpg Missile")
language.Add("weapon_slam","Slam")
language.Add("npc_tripmine","Slam TripMine Mode")
language.Add("npc_satchel","Slam Radio Mode")
language.Add("weapon_physcannon","Gravity Gun")
language.Add("weapon_physgun","Physics Gun")
language.Add("item_item_crate","Supply Crate")
language.Add("item_suit","HEV MARK IV SUIT")